export const HttpResponse = {
    SERVER_ERROR: "Internal server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    USER_ACCOUNT_BLOCKED : "Your account has been blocked.",
    ADMIN_USER_BLOCK : "User blocked successfully",
    ADMIN_USER_UNBLOCK : "User unblocked successfully",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    NO_TOKEN: "Token not provided",
    OTP_INCORRECT: "Incorrect otp, Try again",
    OTP_NOT_FOUND: "Otp not found",
    OTP_RESENDED : "New Otp shared",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_CREATION_FAILED: "User creation failed",
    USER_CREATION_SUCCESS: "User created successfully",
    GOOGLE_LOGIN_SUCCESS: "Logged in with Google successfully",
    LOGIN_SUCCESS : "Welcome back! Login successful.",
    EMAIL_EXIST: "Email already exist",
    INVALID_EMAIL: "Invalid email address",
    RESET_PASS_LINK: "Password reset link sent to your email.",
    TOKEN_EXPIRED: "Token not valid or expired!",
    PASSWORD_CHANGE_SUCCESS: "Password reset successful! Please log in with your new password.",
    UNAUTHORIZED: "Unauthorized access!",
    NO_PAYLOAD: "Payload not found",
    PROFILE_UPDATED : "Profile updated successfully",
    PROFILE_PICTURE_CHANGED: "Profile picture changed successfully",
    LOGOUT_SUCCESS: "You have been logged out successfully",
    INVALID_ID: "Invalid ID format",
    TOO_MANY_REQUESTS: "Too many requests, please try again later.",
    INVALID_USER_ID:"Invalid user ID format",
    ACCESS_TOKEN_EXPIRED : "Access Token Expired",
    UNEXPECTED_KEY_FOUND : "Unexpected key found",
    INVALID_STATUS : 'Invalid status',
    REJECTION_REASON_NOT_PROVIDED : 'Rejection reason is required when rejecting an application',
    APPLICATION_NOT_FOUND : "Application Not Found",
    FILENAME_OR_TYPE_MISSING : "fileName and type are required",
    PRESIGNED_URL_GENERATED : 'Presigned URLs generated successfully',
    KEY_MISSING : "key is required",
    GET_PRESIGNED_URL_GENERATED : 'Get presigned URL generated successfully',
    THERAPIST_ID_MISSING : "Therapist ID is required",
    THERAPIST_ID_AND_DATE_REQUIRED: "Therapist ID and date are required",
    MISSING_FIELDS : "Missing required fields",
    SLOT_CREATED : "Weekly schedule created successfully",
    SLOT_DELETED : "Slot deleted successfully",
    SLOTS_RETRIEVED : "Slots retrieved successfully",
    SLOT_EDITED: "Weekly schedule updated successfully",
    INVALID_SLOT_DATA: "Invalid schedule data",
}; 